# Generated by Django 3.2.23 on 2024-02-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20240202_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='users/default.jpg', upload_to='profile_images'),
        ),
    ]
