# Generated by Django 3.2.23 on 2024-02-11 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='cart',
            field=models.ForeignKey(default=12341423, on_delete=django.db.models.deletion.CASCADE, to='cart.cart'),
            preserve_default=False,
        ),
    ]
