# Generated by Django 3.2 on 2024-02-13 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20240211_2035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItems',
        ),
    ]
