# Generated by Django 3.2 on 2024-03-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
