# Generated by Django 3.2 on 2024-02-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
