# Generated by Django 3.2 on 2024-02-25 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
    ]
