# Generated by Django 3.2 on 2024-02-26 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='paid',
        ),
    ]
