# Generated by Django 3.2 on 2024-03-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_orderitems_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
