# Generated by Django 3.2 on 2024-04-03 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_orderitems_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address1',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='address2',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='age',
            field=models.CharField(default=23, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='county',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=64)),
                ('age', models.CharField(max_length=4)),
                ('address1', models.TextField(blank=True, max_length=100)),
                ('address2', models.TextField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=30)),
                ('phone', models.IntegerField(null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_address', to='orders.order')),
            ],
        ),
    ]
