# Generated by Django 3.2 on 2024-04-03 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_city'),
        ('orders', '0013_auto_20240403_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderaddress',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_address', to='users.profile'),
            preserve_default=False,
        ),
    ]
