# Generated by Django 3.2 on 2024-04-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20240411_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
