# Generated by Django 3.2 on 2024-03-17 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
