# Generated by Django 3.2 on 2024-03-30 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0011_productslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='productslist',
            name='created_by',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, related_name='products_list', to='auth.user'),
            preserve_default=False,
        ),
    ]
