# Generated by Django 3.2 on 2024-03-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productslist_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productslist',
            name='created_by',
        ),
        migrations.AddField(
            model_name='productslist',
            name='user_id',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
