# Generated by Django 3.2 on 2024-03-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20240328_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='product_images/default_image.png', null=True, upload_to='product_images'),
        ),
    ]
